import type { NextPage } from "next";
import Head from "next/head";

import HeaderComponent from "@/components/HeaderComponent";
import Layout from "@/layouts/Layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Yehez-NextTailwind-Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent />
      <Layout>
        <h1 className="text-3xl font-bold underline">Testing</h1>
        <p>hai</p>
      </Layout>
    </div>
  );
};

export default Home;
